### ISSUE TITLE
Feature request: ability to restrict rules in .htmlhintrc to files matching a pattern

### ISSUE THREAD

**Issue by ntdaley** [htmlhint/HTMLHint#127]
When developing for a framework like Angular JS, where we have one main file and a number of files containing html fragments, it would be nice to be able to specify separate rules... e.g. we would want to enforce DOCTYPE on the main index.html file, but not on all of the fragment files.

This can of course be dealt with by running htmlhint twice with separate sets of files, but then for one of those runs, you can't take advantage of htmlhint automatically finding .htmlhintrc in parent folders.

This could for example be implemented by allowing some rules to be restricted to files that matched a pattern.

e.g. That could look something like this:

```
{
   "files-matching" : {
      ".*/index.html$" : {
         "doctype-first" : true,
         "doctype-html5" : true,
         "head-script-disabled" : true,
         "title-require" : true
      }
   },
   "space-tab-mixed-disabled" : true
}
```

where files-matching contains sets of rules that only apply for filenames that match a pattern (in this case files called index.html), and space-tab-mixed-disabled (and any other top-level rules) apply to all files.

There are of course many ways this kind of feature could translate into .htmlhintrc configuration; that's just the first that I thought of.

**Comment by yaniswang** [comment]
htmlhint www/**/*.{htm,html}
	
You can use cli like this.

And if you use htmlhint in another tools, you can develop file filters in tools.

**Comment by shaneknysh** [comment]
@yaniswang Can you point me to some documentation on how to do this? 

I'd like to have the main folder have full rules but have the subfolders omit rules like doctype-first and spec-char-escape but the parent level .htmlhintrc file is read and the subfolder .htmlhintrc rules are ignored. 

I'd also like to have all the rules in one place. So that universally .html files are treated one way and partial files like .hbs or .erb files have a separate set of rules to follow. I can't find any documentation oh how to accomplish this.

**Comment by hepcat72** [comment]
How does one override super-linter's default htmlhint run to ignore files (e.g. Django's html template files that do not conform to htmlhint's requirements)?
