### ISSUE TITLE
Create version of HTMLHint for the browser only

### ISSUE THREAD

**Issue by mehagar** [htmlhint/HTMLHint#316]
**Is your feature request related to a problem? Please describe.**
We want to use HTMLHint in the browser, but there are many dependencies that only seem to be used for the CLI version of HTMLHint.

**Describe the solution you'd like**
A new npm package to be published that only includes the one file necessary to run HTMLHint in a browser.

**Describe alternatives you've considered**
None.

**Additional context**
We are shipping npm dependencies, and we want to avoid having to do a licensing review for all of the current dependencies.

**Comment by Neo-Zhixing** [comment]
The code is now compiled into a umd package with all unnecessary dependencies removed.
```html
<script src="https://cdn.jsdelivr.net/npm/htmlhint@latest/dist/htmlhint.js"></script>
<script>
  let messages = HTMLHint.default.verify('<ul><li></ul>', {'tag-pair': true});
  console.log(messages)
</script>
```

See https://github.com/htmlhint/HTMLHint/wiki/Usage

**Comment by rajsite** [comment]
@Neo-Zhixing I think there was a misunderstanding. The issue was that the htmlhint npm package includes many dependencies because of the CLI.

If we use htmllint then those dependencies end up in our desktop application (similar to an electron application) and having the extra dependencies for the CLI adds a lot of unused packages. It's also slows down builds to install the extra unused packages.

One idea would be to possible have them as separate npm packages. Some examples could be htmlhint-js + htmlhint, or htmlhint-core + htmlhint, or htmlhint +htmlhint-cli, etc. 

As-is the [latest package.json](https://github.com/htmlhint/HTMLHint/blob/bb9a51e407b2ee1cc0173e70326b3ba786cdad69/package.json#L46) still lists lots of dependencies that are useful only for the CLI.

**Comment by Neo-Zhixing** [comment]
Apologies for misunderstanding.
htmlhint + htmlhint-core sounds like a good idea. However it requires a lot more work to be done, and it's probably a breaking change. I'll reopen this issue now.
